org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=false

# Force Gradle to use a specific JDK (use forward slashes to avoid escaping issues)
org.gradle.java.home=C:/Program Files/Java/jdk-17
